# Kawałek kodu testujący parsowanie strony z artykułem

text = """
<div class="newsContent__text" data-io-article-url="https://www.trojmiasto.pl/wiadomosci/Mieszkancy-Nowego-Portu-moga-czuc-odor-ropy-Dlaczego-n179759.html" data-controller="news--poll-placement ga--news news--copy" data-action="\n                click-&gt;ga--news#sendEvent\n
       copy-&gt;news--copy#copy\n                resize@window-&gt;news--poll-placement#place">\n                <div class="component photoMarker 
photoMarker--slider" data-controller="news--slider" data-action="resize@window-&gt;news--slider#resize">\n    <div class="swiper photoMarker__slider" data-news--slider-target="photo">\n        <ul class="swiper-wrapper"><li class="swiper-slide">\n                    <a href="https://s-trojmiasto.pl/zdj/c/n/9/3491/1000x0/3491499-Trwa-rewitalizacja-Szanca-Zachodniego-W-tym-miejscu-powstanie-park.jpg" target="_blank" data-slide-name="647593" data-lightbox-target="photo full" data-sub-html="&lt;h4&gt;\n    \n                    Trwa rewitalizacja Szańca Zachodniego. W tym miejscu powstanie park.\n            \n&lt;/h4&gt;\n\n&lt;p&gt;\n    \n        fot. trojmiasto.pl\n\n            \n&lt;/p&gt;\n" class="photoMarker__link" data-filter-brightness="brightness--100">\n                        <img src="https://s-trojmiasto.pl/zdj/c/n/9/3491/750x637/3491499-Trwa-rewitalizacja-Szanca-Zachodniego-W-tym-miejscu-powstanie-park.jpg" alt="Trwa rewitalizacja Szańca Zachodniego. W tym miejscu powstanie park." data-author="fot. trojmiasto.pl" class="photoMarker__img " data-slider="img" style="aspect-ratio: 1000/764;filter:brightness(1">\n                    </a>\n\n
           <img src="https://s-trojmiasto.pl/zdj/c/n/9/3491/750x600/3491499-Trwa-rewitalizacja-Szanca-Zachodniego-W-tym-miejscu-powstanie-park.jpg" alt="Trwa rewitalizacja Szańca Zachodniego. W tym miejscu powstanie park." class="photoMarker__bg ">\n                </li><li class="swiper-slide">\n                    <a href="https://s-trojmiasto.pl/zdj/c/n/9/3491/1500x0/3491498-Trwa-rewitalizacja-Szanca-Zachodniego-W-tym-miejscu-powstanie-park.jpg" target="_blank" data-slide-name="647592" data-lightbox-target="photo " data-sub-html="&lt;h4&gt;\n    \n                    Trwa rewitalizacja Szańca Zachodniego. W tym miejscu powstanie park.\n            \n&lt;/h4&gt;\n\n&lt;p&gt;\n    \n        fot. trojmiasto.pl\n\n
\n&lt;/p&gt;\n" class="photoMarker__link" data-filter-brightness="brightness--100">\n                        <img src="https://s-trojmiasto.pl/build/assets/svg/placeholder.svg" data-src="https://s-trojmiasto.pl/zdj/c/n/9/3491/750x637/3491498-Trwa-rewitalizacja-Szanca-Zachodniego-W-tym-miejscu-powstanie-park.jpg" alt="Trwa rewitalizacja Szańca Zachodniego. W tym miejscu powstanie park." data-author="fot. trojmiasto.pl" class="photoMarker__img swiper-lazy" data-slider="img" style="aspect-ratio: 1500/1000;filter:brightness(1">\n                    </a>\n\n                    <img src="https://s-trojmiasto.pl/build/assets/svg/placeholder.svg" data-src="https://s-trojmiasto.pl/zdj/c/n/9/3491/750x600/3491498-Trwa-rewitalizacja-Szanca-Zachodniego-W-tym-miejscu-powstanie-park.jpg" alt="Trwa rewitalizacja Szańca Zachodniego. W tym miejscu powstanie park." class="photoMarker__bg 
swiper-lazy">\n                </li></ul>\n\n        <div class="swiper-button-prev"></div>\n        <div class="swiper-button-next"></div>\n\n    
    <div class="photoMarker__counter">\n            <span class="trm trm-camera-shape"></span>\n            <strong>2</strong>\n        </div>\n   
 </div>\n\n    <div class="photoMarker__thumbs">\n        <div class="swiper" data-news--slider-target="nav">\n            <ul class="swiper-wrapper"><li class="swiper-slide">\n                        <img src="https://s-trojmiasto.pl/zdj/c/n/9/3491/150x100/3491499-Trwa-rewitalizacja-Szanca-Zachodniego-W-tym-miejscu-powstanie-park__kr.jpg" alt="Trwa rewitalizacja Szańca Zachodniego. W tym miejscu powstanie park." style="filter:brightness(1);">\n                    </li><li class="swiper-slide">\n                        <img src="https://s-trojmiasto.pl/zdj/c/n/9/3491/150x100/3491498-Trwa-rewitalizacja-Szanca-Zachodniego-W-tym-miejscu-powstanie-park__kr.jpg" alt="Trwa rewitalizacja Szańca Zachodniego. W tym miejscu powstanie park." style="filter:brightness(1);">\n                    </li></ul>\n        </div>\n        <div class="swiper-button-prev" data-news--slider-target="prev"></div>\n        <div class="swiper-button-next" data-news--slider-target="next"></div>\n    </div>\n\n    <div class="photoMarker__footer" data-news--slider-target="footer">\n        <p class="photoMarker__desc" data-news--slider-target="desc">Trwa rewitalizacja Szańca Zachodniego. 
W tym miejscu powstanie park.</p>\n        <p class="photoMarker__author " data-news--slider-target="author">fot. trojmiasto.pl</p>\n    </div>\n</div>\n<p class="lead">Na terenie <a data-tklik="488797" href="https://mapa.trojmiasto.pl/#/location/11.62,82.1/map/11.18,83.73,4,b,0;1;24;37" onclick="openMap(this.href); return false;" target="_blank" title="zobacz na mapie Gdańska">Szańca Zachodniego<img class="icon-map" src="/_img/svg/ico-map-flat.svg" alt="Mapka"></a> trwa remediacja, czyli wymiana gruntów zanieczyszczonych chemicznymi odpadami. W\xa0poniedziałek, 10 lipca rozpoczną 
się prace związane z\xa0usunięciem odpadów smołowatych z\xa0gleby. W\xa0efekcie przez ok. 6 tygodni w\xa0Nowym Porcie może być wyczuwalny odór ropy.</p><br><br>        \n            <div class="component oglCrosslinkWrapper oglCrosslinkWrapper--triple">\n            <h3 class="heading heading--crosslink"><a href="https://ogloszenia.trojmiasto.pl/nieruchomosci-rynek-wtorny/s,na%20morze.html"><strong>Ogłoszenia.trojmiasto.pl</strong>\xa0–\xa0Szukasz mieszkania z widokiem na morze?</a></h3>\n            <div class="oglCrosslink oglCrosslink--nieruchomosci oglCrosslink--triple" data-js-ga="true">\n                <div class="oglCrosslink__wrapper">\n                                                                        <div class="oglCrosslinkItem">\n    <div class="oglCrosslinkItem__picture">\n        <a href="https://ogloszenia.trojmiasto.pl/nieruchomosci-rynek-wtorny/okazale-2-pok-z-widokiem-na-morze-city-park-ogl65298930.html" data-tklik="978039">\n                            <img class="lazy" src="https://s-trojmiasto.pl/build/assets/svg/placeholder.svg" data-src="https://s-trojmiasto.pl/ogloszenia/foto/65300000/65298930/1_6416225_1_42308_900x700.jpg" alt="Okazałe 2-pok. z widokiem na morze | City Park">\n                    </a>\n    </div>\n    <div class="oglCrosslinkItemContent">\n
 <a class="oglCrosslinkItemContent__title" href="https://ogloszenia.trojmiasto.pl/nieruchomosci-rynek-wtorny/okazale-2-pok-z-widokiem-na-morze-city-park-ogl65298930.html" data-tklik="978039">Okazałe 2-pok. z widokiem na morze | City Park</a>\n                    <span class="oglCrosslinkItem__price">\n                790 000 zł\n            </span>\n                            <div class="oglCrosslinkItemContent__loc">Gdańsk, Zaspa</div>\n                <div class="oglCrosslinkItemContentInfo">\n            <span class="oglCrosslinkItemContentInfo__element"><span>2 pokoje</span></span>            <span class="oglCrosslinkItemContentInfo__element"><span>49.8 m<sup>2</sup></span></span>\n        </div>\n    </div>\n</div>\n   
                                                 <div class="oglCrosslinkItem">\n    <div class="oglCrosslinkItem__picture">\n        <a href="https://ogloszenia.trojmiasto.pl/nieruchomosci-rynek-wtorny/widok-na-morze-tyko-200-m-do-bulwaru-ogrod-200m2-ogl65371742.html" data-tklik="978039">\n  
                          <img class="lazy" src="https://s-trojmiasto.pl/build/assets/svg/placeholder.svg" data-src="https://s-trojmiasto.pl/ogloszenia/foto/65370000/65371742/1_7509338_1_22944_900x700.jpg" alt="Widok na morze! Tyko 200 m do Bulwaru! Ogród 200m2">\n                    </a>\n   
 </div>\n    <div class="oglCrosslinkItemContent">\n                <a class="oglCrosslinkItemContent__title" href="https://ogloszenia.trojmiasto.pl/nieruchomosci-rynek-wtorny/widok-na-morze-tyko-200-m-do-bulwaru-ogrod-200m2-ogl65371742.html" data-tklik="978039">Widok na morze! Tyko 200 m do Bulwaru! Ogród 200m2</a>\n                    <span class="oglCrosslinkItem__price">\n                2 480 000 zł\n            </span>\n
                 <div class="oglCrosslinkItemContent__loc">Gdynia, Wzgórze św. Maksymiliana</div>\n                <div class="oglCrosslinkItemContentInfo">\n            <span class="oglCrosslinkItemContentInfo__element"><span>4 pokoje</span></span>            <span class="oglCrosslinkItemContentInfo__element"><span>95 m<sup>2</sup></span></span>\n        </div>\n    </div>\n</div>\n                                                    <div class="oglCrosslinkItem">\n    <div class="oglCrosslinkItem__picture">\n        <a href="https://ogloszenia.trojmiasto.pl/nieruchomosci-rynek-wtorny/1-km-do-morza-od-poludnia-dostepne-od-zaraz-ogl65372654.html" data-tklik="978039">\n                            <img class="lazy" src="https://s-trojmiasto.pl/build/assets/svg/placeholder.svg" data-src="https://s-trojmiasto.pl/ogloszenia/foto/65370000/65372654/1_7531052_1_00018_900x700.jpg" alt="1 km do morza | Od południa | Dostępne od zaraz">\n                    </a>\n    </div>\n    <div class="oglCrosslinkItemContent">\n        
        <a class="oglCrosslinkItemContent__title" href="https://ogloszenia.trojmiasto.pl/nieruchomosci-rynek-wtorny/1-km-do-morza-od-poludnia-dostepne-od-zaraz-ogl65372654.html" data-tklik="978039">1 km do morza | Od południa | Dostępne od zaraz</a>\n                    <span class="oglCrosslinkItem__price">\n                899 000 zł\n            </span>\n                            <div class="oglCrosslinkItemContent__loc">Gdańsk, Letnica</div>\n                <div class="oglCrosslinkItemContentInfo">\n            <span class="oglCrosslinkItemContentInfo__element"><span>3 pokoje</span></span>            <span class="oglCrosslinkItemContentInfo__element"><span>67.48 m<sup>2</sup></span></span>\n        </div>\n    </div>\n</div>\n                                                            </div>\n            </div>\n            <div class="more more--wide">\n        
        <a href="https://ogloszenia.trojmiasto.pl/nieruchomosci-rynek-wtorny/s,na%20morze.html" data-tklik="978039">\n                    Więcej w 
serwisie Ogłoszenia\n                    <span class="more__count">(842)</span>\n                    <span class="trm trm-side-right"></span>\n    
            </a>\n            </div>\n        </div>\n     <br><br><ul class="tableOfContents"><li class="tableOfContents__item">\n            <a class="tableOfContents__link" href="#subtitle_1">Miliony złotych na "oddanie" mieszkańcom Szańca Zachodniego</a>\n        </li><li class="tableOfContents__item">\n            <a class="tableOfContents__link" href="#subtitle_2">250 ton zanieczyszczeń. Może śmierdzieć ropą</a>\n        </li><li class="tableOfContents__item">\n            <a class="tableOfContents__link" href="#subtitle_3">Jakie zanieczyszczenia są na Szańcu Zachodnim?</a>\n        </li></ul>\n\n<script>\n    $(function(){\n        (function () {\n            var links = $(".tableOfContents__link");\n            links.on(\'click\', function(e){\n                e.preventDefault();\n                var href = $(this).attr("href");\n                $(\'html, body\').animate({\n                    scrollTop: $(href).offset().top\n                }, 500);\n            });\n        }());\n    });\n</script>\n<br><br><span id="subtitle_1"></span><h2 class="internal">Miliony złotych na "oddanie" mieszkańcom Szańca Zachodniego</h2><br><br><div data-news--poll-placement-target="inner">\n            <div data-controller="backend--news--poll" data-backend--news--poll-id-value="67455" data-backend--news--poll-new-value="true" data-news--poll-placement-target="content">\n    \n    <div class="newsPoll component" data-controller="news--poll" data-news--poll-loading-class="newsPoll--loading">\n                            <div class="newsPoll__vote" data-news--poll-target="vote">\n                <form method="post" name="ankieta_form" class="newsPoll__container" data-news--poll-target="form">\n                    <h3 class="newsPoll__title"><a href="https://www.trojmiasto.pl/ankiety/Park-na-Szancu-Zachodnim-ank67455.html">Park na Szańcu Zachodnim:</a></h3>\n\n
                                             <label class="newsPoll__option">\n                                <input type="radio" name="l" value="259046" data-action="change-&gt;news--poll#vote">powinien powstać jak najszybciej\n                            </label>\n
                          <label class="newsPoll__option">\n                                <input type="radio" name="l" value="259047" data-action="change-&gt;news--poll#vote">dobrze, że będzie, ale się nie pali, są ważniejsze wydatki\n                            </label>\n
                                 <label class="newsPoll__option">\n                                <input type="radio" name="l" value="259048" data-action="change-&gt;news--poll#vote">to zupełnie niepotrzebna inwestycja\n                            </label>\n                        \n
                                           <input type="hidden" name="id_ankiety" value="67455">\n                            <input type="hidden" 
name="akcja" value="glosowanie">\n                            <input type="hidden" name="ankieta2" value="0">\n
                        </form>\n\n                                    <div class="newsPoll__footer">\n                        <button class="newsPoll__button" data-action="click-&gt;news--poll#showResults">zobacz wyniki <span>(588)</span></button>\n                    </div>\n
\n                <span class="trm trm-loader newsPoll__loader"></span>\n            </div>\n        \n                            <div class="newsPoll__results" data-news--poll-target="results" style="display: none;">\n                <div class="newsPoll__container">\n                    \n 
                   <h3 class="newsPoll__title"><a href="https://www.trojmiasto.pl/ankiety/Park-na-Szancu-Zachodnim-ank67455.html">Park na Szańcu Zachodnim:</a></h3>\n\n                                                                        <div class="newsPoll__option newsPoll__option--result\n                            ">\n                                <span class="newsPoll__text">powinien powstać jak najszybciej</span>\n
                    <span class="newsPoll__percent">63%</span>\n                                <div class="newsPoll__bar" style="width:63.265306122449%;"></div>\n                            </div>\n                                                    <div class="newsPoll__option newsPoll__option--result\n                            ">\n                                <span class="newsPoll__text">dobrze, że będzie, ale się nie pali, są ważniejsze wydatki</span>\n                                <span class="newsPoll__percent">24%</span>\n                                <div class="newsPoll__bar" style="width:24.489795918367%;"></div>\n                            </div>\n                                                    <div class="newsPoll__option newsPoll__option--result\n                            ">\n                                <span class="newsPoll__text">to zupełnie niepotrzebna inwestycja</span>\n                                <span class="newsPoll__percent">13%</span>\n
<div class="newsPoll__bar" style="width:12.244897959184%;"></div>\n                            </div>\n
                </div>\n\n                <div class="newsPoll__footer">\n                                            <span>Łącznie głosów: <b>588</b></span>\n                                        \n                                            <button data-action="click-&gt;news--poll#showVote" class="newsPoll__button">Oddaj głos</button>\n                                    </div>\n            </div>\n            </div>\n\n
</div>\n    </div>\n9 mln zł przeznaczyło miasto na remediację Szańca Zachodniego. Kolejne 4 mln dorzuci Grupa Orlen, która jest prawnym spadkobiercą po dawnej bazie paliw CPN.<br><br><cite>- Dzięki darowiźnie zostanie zrewitalizowany atrakcyjny, sąsiadujący z\xa0Martwą Wisłą teren, na którym 
miasto Gdańsk planuje urządzenie ogólnodostępnego parku. Mieszkańcy odzyskają dzięki temu piękne, położone nad wodą miejsce, które od dawna nie było użytkowane. Działania remediacyjne obejmą rozprowadzenie na rekultywowanym terenie 22 025 m\xa0sześc. gruntu oraz wymianę 5644 m\xa0sześc. gruntu, wykonanie tzw. bentomaty o\xa0powierzchni 2250 m\xa0kw. i\xa0306 mb barier iniekcyjnych.</cite><br>        \n            <div class="component oglCrosslinkWrapper oglCrosslinkWrapper--triple">\n            <h3 class="heading heading--crosslink"><a href="https://ogloszenia.trojmiasto.pl/nieruchomosci-rynek-wtorny/ai,10000_50000,wi,390_330_350_360_370.html"><strong>Ogłoszenia.trojmiasto.pl</strong>\xa0–\xa0Jeśli chcesz kupić działkę, sprawdź okazje od 10 tys. do 50 tys. zł za kawałek zieleni</a></h3>\n            <div class="oglCrosslink oglCrosslink--nieruchomosci oglCrosslink--triple" data-js-ga="true">\n                <div class="oglCrosslink__wrapper">\n
    <div class="oglCrosslinkItem">\n    <div class="oglCrosslinkItem__picture">\n        <a href="https://ogloszenia.trojmiasto.pl/nieruchomosci-rynek-wtorny/dzialka-rod-gdansk-olszynka-ogl65299736.html" data-tklik="929406">\n                            <img class="lazy" src="https://s-trojmiasto.pl/build/assets/svg/placeholder.svg" data-src="https://s-trojmiasto.pl/ogloszenia/foto/65300000/65299736/91545917_1_Dzialka-ROD-Gdansk-Olszynka_900x700.jpg" alt="Działka ROD Gdańsk Olszynka">\n                    </a>\n    </div>\n    <div class="oglCrosslinkItemContent">\n
<a class="oglCrosslinkItemContent__title" href="https://ogloszenia.trojmiasto.pl/nieruchomosci-rynek-wtorny/dzialka-rod-gdansk-olszynka-ogl65299736.html" data-tklik="929406">Działka ROD Gdańsk Olszynka</a>\n                    <span class="oglCrosslinkItem__price">\n                39 000 zł\n            </span>\n                            <div class="oglCrosslinkItemContent__loc">Gdańsk, Olszynka</div>\n                <div class="oglCrosslinkItemContentInfo">\n                        <span class="oglCrosslinkItemContentInfo__element"><span>410 m<sup>2</sup></span></span>\n      
  </div>\n    </div>\n</div>\n                                                    <div class="oglCrosslinkItem">\n    <div class="oglCrosslinkItem__picture">\n        <a href="https://ogloszenia.trojmiasto.pl/nieruchomosci-rynek-wtorny/rod-cegielka-ogl65298896.html" data-tklik="929406">\n     
                       <img class="lazy" src="https://s-trojmiasto.pl/build/assets/svg/placeholder.svg" data-src="https://s-trojmiasto.pl/ogloszenia/foto/65300000/65298896/91540862_5_ROD-Cegielka_900x700.jpg" alt="ROD Cegiełka">\n                    </a>\n    </div>\n    <div class="oglCrosslinkItemContent">\n                <a class="oglCrosslinkItemContent__title" href="https://ogloszenia.trojmiasto.pl/nieruchomosci-rynek-wtorny/rod-cegielka-ogl65298896.html" data-tklik="929406">ROD Cegiełka</a>\n                    <span class="oglCrosslinkItem__price">\n                39 000 zł\n            </span>\n                            <div class="oglCrosslinkItemContent__loc">Gdańsk, Matarnia - Rębiechowo</div>\n
<div class="oglCrosslinkItemContentInfo">\n                        <span class="oglCrosslinkItemContentInfo__element"><span>500 m<sup>2</sup></span></span>\n        </div>\n    </div>\n</div>\n                                                    <div class="oglCrosslinkItem">\n    <div class="oglCrosslinkItem__picture">\n        <a href="https://ogloszenia.trojmiasto.pl/nieruchomosci-rynek-wtorny/ladny-ogrodek-dzialkowy-w-elblagu-ogl65306200.html" data-tklik="929406">\n                            <img class="lazy" src="https://s-trojmiasto.pl/build/assets/svg/placeholder.svg" data-src="https://s-trojmiasto.pl/ogloszenia/foto/65310000/65306200/91574666_4_Ladny-ogrodek-dzialkowy-w-Elblagu_900x700.jpg" alt="Ładny ogródek działkowy w Elblągu">\n                    </a>\n    </div>\n    <div class="oglCrosslinkItemContent">\n                <a class="oglCrosslinkItemContent__title" href="https://ogloszenia.trojmiasto.pl/nieruchomosci-rynek-wtorny/ladny-ogrodek-dzialkowy-w-elblagu-ogl65306200.html" data-tklik="929406">Ładny ogródek działkowy w Elblągu</a>\n                    <span class="oglCrosslinkItem__price">\n                10 000 zł\n            </span>\n  
                          <div class="oglCrosslinkItemContent__loc">Elbląg</div>\n                <div class="oglCrosslinkItemContentInfo">\n      
                  <span class="oglCrosslinkItemContentInfo__element"><span>312 m<sup>2</sup></span></span>\n        </div>\n    </div>\n</div>\n   
                                                         </div>\n            </div>\n            <div class="more more--wide">\n                <a 
href="https://ogloszenia.trojmiasto.pl/nieruchomosci-rynek-wtorny/ai,10000_50000,wi,390_330_350_360_370.html" data-tklik="929406">\n
     Więcej w serwisie Ogłoszenia\n                    <span class="more__count">(76)</span>\n                    <span class="trm trm-side-right"></span>\n                </a>\n            </div>\n        </div>\n    <br><br><span id="subtitle_2"></span><h2 class="internal">250 ton zanieczyszczeń. Może śmierdzieć ropą</h2><br><br>Prace na terenie Szańca Zachodniego już trwają. W\xa0poniedziałek robotnicy rozpoczną usuwanie odpadów z\xa0gleby.<br><br><cite>- Ten etap prac może potrwać do ok. 6 tygodni, konieczne jest bowiem usunięcie co najmniej 250 ton zanieczyszczeń. W\xa0związku z\xa0tym, w\xa0rejonie ich prowadzenia możliwe będzie odczuwanie wzmożonej woni substancji ropopochodnych - zapowiada <b>Aneta Niezgoda</b> z\xa0Dyrekcji Rozbudowy Miasta Gdańska.</cite><br>        \n            <div class="component oglCrosslinkWrapper oglCrosslinkWrapper--triple">\n        
    <h3 class="heading heading--crosslink"><a href="https://ogloszenia.trojmiasto.pl/nieruchomosci-mam-do-wynajecia/s,rzeka,ot,1.html"><strong>Ogłoszenia.trojmiasto.pl</strong>\xa0–\xa0Nie do kupienia, ale można wynająć. Z widokiem na rzekę</a></h3>\n            <div class="oglCrosslink oglCrosslink--nieruchomosci oglCrosslink--triple" data-js-ga="true">\n                <div class="oglCrosslink__wrapper">\n
                                          <div class="oglCrosslinkItem">\n    <div class="oglCrosslinkItem__picture">\n        <a href="https://ogloszenia.trojmiasto.pl/nieruchomosci-mam-do-wynajecia/apartament-z-widokiem-na-rzeke-ogl65237517.html" data-tklik="993623">\n
     <img class="lazy" src="https://s-trojmiasto.pl/build/assets/svg/placeholder.svg" data-src="https://s-trojmiasto.pl/ogloszenia/foto/65240000/65237517/1_7052280_1_44737_900x700.jpg" alt="Apartament z widokiem na rzekę!">\n                    </a>\n    </div>\n    <div class="oglCrosslinkItemContent">\n                <a class="oglCrosslinkItemContent__title" href="https://ogloszenia.trojmiasto.pl/nieruchomosci-mam-do-wynajecia/apartament-z-widokiem-na-rzeke-ogl65237517.html" data-tklik="993623">Apartament z widokiem na rzekę!</a>\n                    <span class="oglCrosslinkItem__price">\n                5 000 zł\n            </span>\n                            <div class="oglCrosslinkItemContent__loc">Gdańsk, Długie Ogrody</div>\n                <div class="oglCrosslinkItemContentInfo">\n            <span class="oglCrosslinkItemContentInfo__element"><span>2 pokoje</span></span>            <span class="oglCrosslinkItemContentInfo__element"><span>60 m<sup>2</sup></span></span>\n        </div>\n    </div>\n</div>\n                                                    <div class="oglCrosslinkItem">\n    <div class="oglCrosslinkItem__picture">\n        <a href="https://ogloszenia.trojmiasto.pl/nieruchomosci-mam-do-wynajecia/przytulnie-umeblowane-mieszkanie-2-pok-54-m2-dostepne-od-1-wrzesnia-ogl65368674.html" data-tklik="993623">\n                            <img class="lazy" src="https://s-trojmiasto.pl/build/assets/svg/placeholder.svg" data-src="https://s-trojmiasto.pl/ogloszenia/foto/65370000/65368674/91904672_1_Przytulnie-umeblowane-mieszkanie-2-pok-54-m2-dostepne-od-1-wrzesnia_900x700.jpg" alt="Przytulnie umeblowane mieszkanie 2 pok. 54 m2, dostępne od 1.września">\n                    </a>\n    </div>\n    <div class="oglCrosslinkItemContent">\n                <a class="oglCrosslinkItemContent__title" href="https://ogloszenia.trojmiasto.pl/nieruchomosci-mam-do-wynajecia/przytulnie-umeblowane-mieszkanie-2-pok-54-m2-dostepne-od-1-wrzesnia-ogl65368674.html" data-tklik="993623">Przytulnie umeblowane mieszkanie 2 pok. 54 m2, dostępne...</a>\n                    <span class="oglCrosslinkItem__price">\n                1 900 zł\n            </span>\n
       <div class="oglCrosslinkItemContent__loc">Rumia, Biała Rzeka</div>\n                <div class="oglCrosslinkItemContentInfo">\n            <span class="oglCrosslinkItemContentInfo__element"><span>2 pokoje</span></span>            <span class="oglCrosslinkItemContentInfo__element"><span>54 m<sup>2</sup></span></span>\n        </div>\n    </div>\n</div>\n                                                    <div class="oglCrosslinkItem">\n    <div class="oglCrosslinkItem__picture">\n        <a href="https://ogloszenia.trojmiasto.pl/nieruchomosci-mam-do-wynajecia/sloneczne-ciche-z-widokiem-na-rzeke-ogl65342978.html" data-tklik="993623">\n                            <img class="lazy" src="https://s-trojmiasto.pl/build/assets/svg/placeholder.svg" data-src="https://s-trojmiasto.pl/ogloszenia/foto/65340000/65342978/1_7393866_1_14938_900x700.jpg" alt="Słoneczne, ciche z widokiem na rzekę">\n                    </a>\n    </div>\n    <div class="oglCrosslinkItemContent">\n                <a class="oglCrosslinkItemContent__title" href="https://ogloszenia.trojmiasto.pl/nieruchomosci-mam-do-wynajecia/sloneczne-ciche-z-widokiem-na-rzeke-ogl65342978.html" data-tklik="993623">Słoneczne, ciche z widokiem na rzekę</a>\n                    <span class="oglCrosslinkItem__price">\n                4 500 zł\n
 </span>\n                            <div class="oglCrosslinkItemContent__loc">Gdańsk, Śródmieście</div>\n                <div class="oglCrosslinkItemContentInfo">\n            <span class="oglCrosslinkItemContentInfo__element"><span>3 pokoje</span></span>            <span class="oglCrosslinkItemContentInfo__element"><span>75 m<sup>2</sup></span></span>\n        </div>\n    </div>\n</div>\n
             </div>\n            </div>\n            <div class="more more--wide">\n                <a href="https://ogloszenia.trojmiasto.pl/nieruchomosci-mam-do-wynajecia/s,rzeka,ot,1.html" data-tklik="993623">\n                    Więcej w serwisie Ogłoszenia\n                    <span class="more__count">(4)</span>\n                    <span class="trm trm-side-right"></span>\n                </a>\n            </div>\n        </div>\n    <br><br>Smoła i\xa0substancje podobnego pochodzenia muszą zostać usunięte z\xa0gleby na terenie Szańca Zachodniego. Taką konieczność wskazano 
również w\xa0decyzji Regionalnej Dyrekcji Ochrony Środowiska. Wykonawcą prac jest firma Hydrogeotechnika.<br><br><span id="subtitle_3"></span><h2 class="internal">Jakie zanieczyszczenia są na Szańcu Zachodnim?</h2><br><br><strong>Przypomnijmy:</strong> Problemem na Szańcu Zachodnim jest znaczące przekroczenie stężenia zanieczyszczeń związkami ropopochodnymi. Na tym terenie funkcjonowała od 1906 r. baza paliw do bunkrowania okrętów i\xa0statków, a\xa0później - w\xa0latach 80. XX w. - baza paliw Petrochemii Płock.<br>  <br>Badania laboratoryjne próbek gruntu, które zostały pobrane ze wspomnianego terenu, wykonane do projektu planu remediacji, wykazały przekroczenia dopuszczalnych zawartości w\xa0glebie oraz dopuszczalne zawartości w\xa0ziemi, np.: <ul class="bullet-list"><li>składników benzyn (przy maksymalnej dopuszczalnej zawartości (w mg/kg suchej masy) wynoszącej 50, 
sięgające: 14728, 14140, 14284) </li><li>czy składników oleju (przy maksymalnej dopuszczalnej zawartości (w mg/kg suchej masy) wynoszącej 1000, sięgające: 4509, 4722, 6014, 8901, 10 606, 19 056, 21 791).</li></ul>\n                <div class="newsPollWrapper" data-news--poll-placement-target="below"></div>\n                <div class="lightboxVerticalGallery" data-lightbox-target="vertical">\n    <div class="lightboxVerticalGallery__list" data-lightbox-target="verticalList"></div>\n    <button class="lightboxVerticalGallery__close" data-action="click-&gt;lightbox#closeSlider"><span class="trm trm-ico-maly-x"></span></button>\n</div>\n            </div>
"""

from bs4 import BeautifulSoup, Tag
import re
soup = BeautifulSoup(text, 'html.parser')

for el in soup.find_all("div", "photoMarker"):
    el.decompose()
for el in soup.find_all("div", "oglCrosslinkWrapper"):
    el.decompose()
for el in soup.find_all("div", "newsPoll"):
    el.decompose()
for el in soup.find_all("ul", "tableOfContents"):
    el.decompose()


# for child in soup.div.children:
#      if isinstance(child, Tag):
#         # and child.name =='h3'
#         print(child.name)
#         # soup.extract(child)
text = soup.get_text().strip()
text = re.sub(r"([^.!?,\n])\n\n",r"\1.\n", text)
text = text.replace("\n", " ")
text = text.replace("  ", " ")
text = text.replace("  ", " ")
print("===")
print(text)
print("===")